#Default Compiler
CC = g++

#Compiler Flags
#  -g		Adds debugging information to the executable file
#  -Wall	Turns on most, but not all, compiler warnings
CFLAGS = -g -Wall

#Main Executable
run: #Insert Here
	$(CC) $(CFLAGS) #Insert Here

#Object Files
